get_traffic_ranking:
get_protocol_stats:
  fields:
    mac:
      required: true
      example: "10:b7:13:91:21:9b"
      selector:
        text:
    ip:
      required: false
      example: "10.10.10.158"
      selector:
        text:
get_offline_history:
add_mac_rule:
  fields:
    mac:
      required: true
      example: "08:9b:4b:00:10:2e"
      selector:
        text:
    tagname:
      required: false
      example: "孩子平板限网"
      selector:
        text:
    expires:
      required: false
      default: 0
      selector:
        number:
          min: 0
          mode: box
delete_mac_rule:
  fields:
    rule_id:
      required: true
      selector:
        number:
          min: 1
          mode: box